### ISSUE TITLE
Clean up project

### ISSUE THREAD

**Issue by MarinTrpenovski** [AngelaM123/Servlets_JSP-Pages#1]
Remove classes and code that is not used. This project is for JSP pages and have servlets just for entities that are in DB. I found some servlets that are not need or used in the project. They can be removed. Also they can be removed from configuration file (web.xml). @AngelaM123

**Comment by AngelaM123** [comment]
I removed the servlets and classes that were not in use as well as removed them form the web.xml file, please check my updates and let me know if I have to make other changes as well @MarinTrpenovski

**Comment by MarinTrpenovski** [comment]
Thanks @AngelaM123 . This issue can be closed and marked as completed.
