### ISSUE TITLE
Update Readme file of project

### ISSUE THREAD

**Issue by MarinTrpenovski** [AngelaM123/Servlets_JSP-Pages#3]
Update documentation of project. 
Readme file should have short overview of what is business logic of the project.
What technologies are used for the project ?
What tools are needed in order to start project locally ?
How to build project ?
How to start project locally, need to describe each of the steps that need to be executed in order new users that will clone the project from repository to be able to start project locally without any assistance. 
Need to add .gitignore file to the project.
@AngelaM123 You can start work on this.

**Comment by AngelaM123** [comment]
The project documentation has been updated and .gitignore file has been added.
All the question points have been addressed and I hope all the necessary steps of running the project have been given.

**Comment by MarinTrpenovski** [comment]
Looks good.
In .gitignore add folder which shouldn't be tracked by git and that are not needed for project. Like .idea, target folders.

I find commented code in the classes, please remove it . 
Also add hashcode and equals methods in DTO classes.
In interfaces add one line empty between methods. It should more readable when have space between methods.

@AngelaM123 Please apply this changes.

**Comment by AngelaM123** [comment]
I have deleted the comments and I have added the folders .idea and target into the .gitignore file I also added the hashcode and equals methods

**Comment by MarinTrpenovski** [comment]
This issue is done.
